### PR TITLE
Update StudentProjects.vue

### PR DESCRIPTION
**Pull request by yaja95**
Creates a filter button that displays the selection menu on click.
!PROBLEM! When using the clearable x, the select menu pops up to the left of the button randomly.

### CODE REVIEW

**Comment by CAD97** [comment]
@yaja95 update?

**Comment by yaja95** [comment]
I have the add post button in a different position but it's not as aesthetically pleasing as I'd like. As for the filter issue, I haven't been able figure out how to prevent it from realigning  to the left of the filter button yet, or how to make the filter button move with the select dialog once it's open.

**Comment by yaja95** [comment]
Check this please @CAD97

**Comment by yaja95** [comment]
Can you merge this one also @brandonp1551

**Comment by brandonp1551** [comment]
Actually can't merge it, no. There's file conflicts.

**Comment by yaja95** [comment]
I actually think I made the changes in the faculty-scholars branch. I'll check really quick.

**Comment by yaja95** [comment]
We're good. This branch can be deleted.

**Pull request closed without merging**
